name: link-ci

on:
  push:
    branches: [master]
    paths:
      - "packages/link/**"

jobs:
  call-workflow-install:
    uses: ./.github/workflows/reusable.yml
    with:
      username: duang
  build:
    runs-on: ubuntu-latest
    steps:
      - run: yarn deploy
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
          GITHUB_CNAME: test1.qdzhou.cn
          GITHUB_URL: test-lerna-link
          PACKAGE_NAME: link
