name: link-blog-ci

on:
  push:
    branches: [master]
    paths:
      - "packages/link/**"

jobs:
  call-workflow-install:
    uses: ./.github/workflows/reusable.yml
    with:
      username: duang
  build:
    needs: call-workflow-install
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2 # 安装nodejs
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn deploy
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
          GITHUB_CNAME: test1.qdzhou.cn
          GITHUB_URL: test-lerna-link
          PACKAGE_NAME: link
