name: link-blog-ci

on:
  push:
    branches: [master]
    paths:
      - "packages/link/**"

jobs:
  call-workflow-install:
    uses: ./.github/workflows/reusable.yml
    with:
      username: duang
  build:
    needs: call-workflow-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm -rf node_modules
      - run: yarn
      - run: yarn deploy
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
          GITHUB_CNAME: link.aduang.cn # 自定义域名
          GITHUB_URL: link # github地址
          PACKAGE_NAME: link # packages/名称
