name: link

on:
  push:
    branches: [master]
    paths:
      - "packages/link/**"

jobs:
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: yarn deploy
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
          GITHUB_CNAME: test1.qdzhou.cn
          GITHUB_URL: test-lerna-link
          PACKAGE_NAME: link
