name: react

on:
  push:
    branches: [master]
    paths:
      - "packages/react/**"

jobs:
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: yarn deploy
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
          GITHUB_CNAME: test2.qdzhou.cn
          GITHUB_URL: test-lerna-react
          PACKAGE_NAME: react
