name: react-blog-ci

on:
  push:
    branches: [master]
    paths:
      - "packages/react/**"

jobs:
  call-workflow-install:
    uses: ./.github/workflows/reusable.yml
    with:
      username: duang
  build:
    needs: call-workflow-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn deploy
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
          GITHUB_CNAME: test2.qdzhou.cn
          GITHUB_URL: test-lerna-react
          PACKAGE_NAME: react
